const SkillGap = require('../models/SkillGap.model')
const Analytics = require('../models/Analytics.model')

module.exports = {
  calculateSkillGaps: async (req, res) => {
    if (!req.user || !req.user.university) {
      return res
        .status(400)
        .json({ error: 'User not authenticated or university not specified' })
    }
    const skills = [
      'JavaScript',
      'Python',
      'Cloud',
      'AI',
      'Data Science',
      'Cybersecurity',
      'Blockchain',
      'DevOps',
      'UI/UX Design',
      'Mobile Development',
      'Project Management',
      'Soft Skills',
      'Agile Methodologies',
      'Machine Learning',
      'Big Data',
      'Internet of Things (IoT)',
      'Virtual Reality (VR)',
      'Augmented Reality (AR)',
      'Quantum Computing',
      'Robotics',
      'Ethical Hacking',
      'Network Security',
      'Web Development',
      'Game Development',
      'Database Management',
      'Business Intelligence',
      'Digital Marketing',
      'E-commerce',
      'Content Creation',
      'SEO Optimization',
      'Social Media Management',
      'Cloud Computing',
      'IT Support',
      'Technical Writing',
      'Data Visualization',
      'Data Analytics',
      'Mobile App Development',
      'Software Testing',
      'Quality Assurance',
      'Systems Analysis',
      'IT Project Management',
      'Information Security',
      'Network Administration',
      'Hardware Engineering',
      'Software Engineering',
      'Game Design',
      'Web Design',
      'Graphic Design',
      'User Experience (UX) Design',
      'User Interface (UI) Design',
      'Content Management Systems (CMS)',
      'Search Engine Marketing (SEM)',
      'Email Marketing',
      'Affiliate Marketing',
      'Brand Management',
      'Public Relations (PR)',
      'Event Planning',
      'Sales Strategy',
      'Customer Relationship Management (CRM)',
      'Business Development',
      'Entrepreneurship',
      'Financial Analysis',
      'Investment Strategies',
      'Risk Management',
      'Supply Chain Management',
      'Logistics Management',
      'Operations Management',
      'Human Resources (HR)',
      'Talent Acquisition',
      'Employee Relations',
      'Training and Development',
      'Organizational Development',
      'Performance Management',
      'Compensation and Benefits',
      'Labor Relations',
      'Workforce Planning',
      'Diversity and Inclusion',
      'Change Management',
      'Strategic Planning',
      'Business Process Improvement',
      'Lean Six Sigma',
      'Agile Project Management',
      'Scrum Master Certification',
      'ITIL Certification',
      'Certified Information Systems Security Professional (CISSP)',
      'Certified Ethical Hacker (CEH)',
      'Cisco Certified Network Associate (CCNA)',
      'Microsoft Certified Solutions Expert (MCSE)',
      'Amazon Web Services (AWS) Certified Solutions Architect',
      'Google Cloud Certified - Professional Cloud Architect',
      'Certified Data Professional (CDP)',
      'Certified Business Analysis Professional (CBAP)',
      'Project Management Professional (PMP)',
      'Certified ScrumMaster (CSM)',
      'Certified Information Systems Auditor (CISA)',
      'Certified Information Security Manager (CISM)',
      'CompTIA A+',
      'CompTIA Network+',
      'CompTIA Security+',
      'CompTIA Cloud+',
      'CompTIA Project+',
      'CompTIA IT Fundamentals (ITF+)',
      'CompTIA Linux+',
      'CompTIA Server+',
      'CompTIA Cybersecurity Analyst (CySA+)',
      'CompTIA Advanced Security Practitioner (CASP+)',
      'Certified Kubernetes Administrator (CKA)',
      'Certified Kubernetes Application Developer (CKAD)',
      'Docker Certified Associate',
      'Red Hat Certified System Administrator (RHCSA)',
      'Red Hat Certified Engineer (RHCE)',
      'Oracle Certified Professional, Java SE Programmer',
      'Microsoft Certified: Azure Fundamentals',
      'Microsoft Certified: Azure Solutions Architect Expert',
      'Google Associate Cloud Engineer',
      'Google Professional Data Engineer',
      'Salesforce Certified Administrator',
      'Salesforce Certified Advanced Administrator',
      'Salesforce Certified Platform App Builder',
      'Natural Language Processing (NLP)',
      'Chatbot Development',
      'Prompt Engineering',
      'Edge Computing',
      'SaaS Development',
      'PaaS Architecture',
      'IaaS Management',
      'API Development',
      'API Security',
      'RESTful APIs',
      'GraphQL',
      'gRPC',
      'Event-Driven Architecture',
      'Microservices Architecture',
      'Monorepo Management',
      'CI/CD Pipelines',
      'GitOps',
      'Infrastructure as Code (IaC)',
      'Terraform',
      'Ansible',
      'Jenkins',
      'GitHub Actions',
      'CircleCI',
      'Bitbucket Pipelines',
      'Kubernetes Helm',
      'Serverless Computing',
      'AWS Lambda',
      'Azure Functions',
      'Firebase',
      'Progressive Web Apps (PWA)',
      'Responsive Design',
      'Tailwind CSS',
      'SASS/SCSS',
      'React.js',
      'Next.js',
      'Vue.js',
      'Nuxt.js',
      'Angular',
      'Svelte',
      'Express.js',
      'Node.js',
      'NestJS',
      'Deno',
      'Spring Boot',
      'Django',
      'Flask',
      'FastAPI',
      'Laravel',
      'Ruby on Rails',
      'ASP.NET Core',
      'Go (Golang)',
      'Rust',
      'C/C++',
      'R Programming',
      'Matlab',
      'TypeScript',
      'NoSQL Databases',
      'MongoDB',
      'Cassandra',
      'Redis',
      'PostgreSQL',
      'MySQL',
      'SQL Server',
      'Firebase Realtime Database',
      'Google Firestore',
      'Hadoop',
      'Spark',
      'Kafka',
      'Elasticsearch',
      'Logstash',
      'Prometheus',
      'Grafana',
      'Splunk',
      'Power BI',
      'Tableau',
      'Looker',
      'QlikView',
      'Snowflake',
      'Data Warehousing',
      'ETL Tools',
      'Data Engineering',
      'Data Governance',
      'Cyber Forensics',
      'Penetration Testing',
      'Bug Bounty',
      'SOC Operations',
      'DevSecOps',
      'Zero Trust Architecture',
      'SIEM',
      'Cloud Security',
      'IAM',
      'OAuth2.0',
      'OpenID Connect',
      'SAML',
      'Penetration Testing Tools (e.g. Burp Suite, Metasploit)',
    ]

    const results = []

    for (const skill of skills) {
      const industryDemand = Math.floor(Math.random() * 100)
      const studentProficiency = Math.floor(Math.random() * 80)
      const gap = industryDemand - studentProficiency

      const record = await SkillGap.create({
        university: req.user.university,
        skill,
        industryDemand,
        studentProficiency,
        gap,
      })

      await Analytics.create({
        university: req.user.university,
        type: 'skill_gap',
        data: record,
        period: {
          start: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
          end: new Date(),
        },
      })

      results.push(record)
    }

    res.json(results)
  },
}
